apiVersion: v1
kind: Service
metadata:
  name: node-port
spec:
  type: NodePort # add type
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30080 # set host(node) port
  selector:
    run: cluster-ip
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-port
  name: node-port
spec:
  containers:
  - image: nginx
    name: cluster-ip
    ports:
    - containerPort: 80
